%if #{XDG_CONFIG_HOME}
  TMUX_CONFIG_HOME="$XDG_CONFIG_HOME/tmux"
%else
  TMUX_CONFIG_HOME="$HOME/.config/tmux"
%endif

%if #{XDG_DATA_HOME}
TMUX_PLUGIN_MANAGER_PATH="$XDG_DATA_HOME/tpm/plugins"
%else
TMUX_PLUGIN_MANAGER_PATH="$HOME/.local/share/tpm/plugins"
%endif

source-file "$TMUX_CONFIG_HOME/tmux.options.conf"

source-file "$TMUX_CONFIG_HOME/tmux.bind.conf"

# TPM Configuration

if "test ! -d $TMUX_PLUGIN_MANAGER_PATH/tpm" \
  "run 'git clone https://github.com/tmux-plugins/tpm $TMUX_PLUGIN_MANAGER_PATH/tpm && $TMUX_PLUGIN_MANAGER_PATH/tpm/bin/install_plugins'"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'egel/tmux-gruvbox'

set -g @tmux-gruvbox 'dark'

run "$TMUX_PLUGIN_MANAGER_PATH/tpm/tpm"
