# Make `<prefix> R` reload the config file
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded"

# Clipboard (wl-clipboard)
#   copy mode: y -> system clipboard
#   prefix p  -> system clipboard into tmux and paste
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"
bind p run "wl-paste -n | tmux load-buffer - ; tmux paste-buffer"

bind -r C-h run "tmux select-pane -L"
bind -r C-j run "tmux select-pane -D"
bind -r C-k run "tmux select-pane -U"
bind -r C-l run "tmux select-pane -R"
