set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g mouse on                       # enable mouse: switch panes/windows, scroll, resize
set -g focus-events on                # pass focus in/out events to applications (needed by nvim)
set -g escape-time 0                  # no ESC delay for key combos
set -g history-limit 9000             # scrollback buffer size (lines)

# Windows/panes numbered from 1, renumber on close
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

