[general]
import = ["~/.cache/wal/colors-alacritty.toml"]

[terminal.shell]
program = "/usr/bin/bash"
args = ["-lc", "$HOME/.local/bin/tmux-launch.sh"]

[window]
dynamic_padding = true
padding = { x = 30, y = 15 }
decorations = "Transparent"
opacity = 0.3

[mouse]
hide_when_typing = true
