[general]
import = [
  "~/.cache/wal/colors-alacritty.toml"
]

[terminal.shell]
program = "/usr/bin/tmux"
args = ["new-session", "-A", "-s", "base"]

[window]
dynamic_padding = true
padding = { x = 30, y = 15}
decorations = "Transparent"
opacity = 0.8

[font]
normal = { family = "0xProto Nerd Font", style = "Regular" }
bold = { family = "0xProto Nerd Font", style = "Bold" }
italic = { family = "0xProto Nerd Font", style = "Italic" }
